### ISSUE TITLE
ANTLR version

### ISSUE THREAD

**Issue by Farbs** [freds72/poom-sdk#1]
Running the wad_reader tool spits out several lines like this:

ANTLR runtime and generated code versions disagree: 4.9!=4.8

I'm guessing this is because ANTLR version 4.9 has been released, so the setup requirement below pulls the new version rather than the required 4.8:

antlr4-python3-runtime>=4.8

I'm not familiar with the python package installer, but could this be fixed by changing the >= to == ?

**Comment by freds72** [comment]
fixed in wad_reader 3.9
