### ISSUE TITLE
Generating multiple maps

### ISSUE THREAD

**Issue by gaekwad** [freds72/poom-sdk#3]
This is less of an issue and just a question about the tool.  How do you use it to create multiple maps as one episode? I notice the ZMAPINFO supplied in the repo has E1M1 as the first level and E1M3 as the next, but compiling using the example given only creates E1M1, which when beaten, goes to the end screen.

**Comment by freds72** [comment]
launch the compiler without the —map parameter, that will pack all maps declared in mapinfo.
